### PR TITLE
CI/CD pipeline

### PR DESCRIPTION
**Pull request by kicr1**
CI/CD pipeline from existing codebase ported

### CODE REVIEW

**Comment by kicr1** [comment]
Test

**Review by vicr1 — DISMISSED** [review]
DO NOT MERGE, testing repo settings

**Review by vicr1 — DISMISSED** [review]
DO NOT MERGE

**Review by vicr1 — APPROVED** [review]
TEST

**Review by vicr1 — APPROVED** [review]

**Pull request merged**
